### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by 1003824904** [JMCuixy/swagger2word#16]
java.lang.StackOverflowError: null
	at java.lang.String.substring(String.java:1969)
	at java.lang.String.split(String.java:2353)
	at java.lang.String.split(String.java:2422)
	at org.word.service.impl.WordServiceImpl.parseRef(WordServiceImpl.java:191)
	at org.word.service.impl.WordServiceImpl.parseRef(WordServiceImpl.java:212)
	at org.word.service.impl.WordServiceImpl.parseRef(WordServiceImpl.java:212)

**Comment by miRUAcleInjoker** [comment]
同

**Comment by ChangRC** [comment]
parseRef方法有bug,能不能处理一下？

**Comment by ChangRC** [comment]
我做了一下小修改，兼容自己的场景

private ObjectNode parseRef(List<String> sourceRef,String ref, Map<String, Object> map) {
        ObjectNode objectNode = JsonUtils.createObjectNode();
        if (StringUtils.isNotEmpty(ref) && ref.startsWith("#")) {
            String[] refs = ref.split("/");
            Map<String, Object> tmpMap = map;
            //取出ref最后一个参数 start
            for (String tmp : refs) {
                if (!"#".equals(tmp)) {
                    tmpMap = (Map<String, Object>) tmpMap.get(tmp);
                }
            }
            //取出ref最后一个参数 end
            //取出参数
            Map<String, Object> properties = (Map<String, Object>) tmpMap.get("properties");
            if (properties == null) {
                return objectNode;
            }
            Set<String> keys = properties.keySet();
            //遍历key
            for (String key : keys) {
                Map<String, Object> keyMap = (Map) properties.get(key);
                if ("array".equals(keyMap.get("type"))) {
                    //数组的处理方式
                    String sonRef = (String) ((Map) keyMap.get("items")).get("$ref");
                    if (sourceRef.contains(sonRef))
                        continue;
                    sourceRef.add(sonRef);
                    JsonNode jsonNode = parseRef(sourceRef,sonRef, map);
                    ArrayNode arrayNode = JsonUtils.createArrayNode();
                    arrayNode.add(jsonNode);
                    objectNode.set(key, arrayNode);
                } else if (keyMap.get("$ref") != null) {
                    //对象的处理方式
                    String sonRef = (String) keyMap.get("$ref");
                    if (sourceRef.contains(sonRef))
                        continue;
                    sourceRef.add(sonRef);
                    ObjectNode object = parseRef(sourceRef,sonRef, map);
                    objectNode.set(key, object);
                } else {
                    //其他参数的处理方式，string、int
                    String str = "";
                    if (keyMap.get("description") != null) {
                        str = str + keyMap.get("description");
                    }
                    if (keyMap.get("format") != null) {
                        str = str + String.format("格式为(%s)", keyMap.get("format"));
                    }
                    objectNode.put(key, str);
                }
            }
        }
        return objectNode;
    }

**Comment by skylinehyc** [comment]
同样遇到了，有解决的吗

**Comment by ChangRC** [comment]
我贴的代码不行？
